carn:
    scale: 4
    channel: 3
    multi_scale: 1  # change to 1 if use official pth file
    group: 1
    clip: 10

batch_shape: [16, 3, 64, 64]
lr: 1.0e-4
lr_decay:
    method: multistep
    decay_step: [500]
    decay_rate: 0.1
