---
edrn:
    scale: 1
    channel: 3
    G0: 64
    EDRNkSize: 3
    EDRNconfig: B
    rgb_range: 255

batch_shape: [16, 3, 32, 32]
lr: 1.0e-4
lr_decay:
    method: multistep
    decay_step: [500]
    decay_rate: 0.1
