ffdnet:
    scale: 1
    channel: 3
    n_layers: 10
    level: 0
    training: true

batch_shape: [16, 3, 32, 32]
lr: 1.0e-4
lr_decay:
    method: multistep
    decay_step: [500]
    decay_rate: 0.1
