---
rbpn:
    scale: 4
    channel: 3
    depth: 7
    residual: false
    base_filter: 256
    feat: 64
    num_stages: 3
    n_resblock: 5

batch_shape: [4, 3, 16, 16]
lr: 1.0e-4
lr_decay:
    method: multistep
    decay_step: [500]
    decay_rate: 0.1
