srfeat:
    channel: 3
    scale: 4
    filters: 64
    num_residualblocks: 16
    weights: [1, 0.01, 0.01]
    patch_size: 64

batch_shape: [16, 3, 16, 16]
lr: 1.0e-4
lr_decay:
    method: multistep
    decay_step: [500]
    decay_rate: 0.1
