# srcnn 9-5-5
---
srcnn:
    layers: 3
    filters:
        - 9
        - 1
        - 5
    scale: 4
    channel: 1

batch: 4
patch_size: 16
lr: 1.0e-4
lr_decay:
    method: multistep
    decay_step: [10000, 15000]
    decay_rate: 0.1
