# espcn 5-3-3
---
espcn:
    layers: 3
    filters: [64, 32, 32]
    kernel: [5, 3, 3]
    scale: 4
    channel: 3

batch_shape: [16, 16, 16, 3]
lr: 1.0e-2
lr_decay:
    method: multistep
    decay_step: [10000, 15000]
    decay_rate: 0.1
