# note our rdn implementation has fewer layers than paper's
# (hard to train...)
---
rdn:
    rdb_blocks: 8
    rdb_conv: 8
    global_filters: 64
    rdb_filters: 64
    scale: 4
    channel: 3

batch: 16
patch_size: 64
lr: 1.0e-4
