# srcnn 9-5-5
---
srcnn:
    layers: 3
    kernel:
        - 9
        - 5
        - 5
    custom_upsample: false
    scale: 4
    channel: 1

batch: 4
patch_size: 64
lr: 1.0e-2
lr_decay:
    method: multistep
    decay_step: [10000, 15000]
    decay_rate: 0.1
